version: '3.8'

services:
  garpix_postgres:
    container_name: garpix_postgres
    image: postgres:15
    env_file: 
      - backend/.env
    volumes:
      - ./backend/database/:/docker-entrypoint-initdb.d
      - ./backend/database/data:/var/lib/postgresql/data
    restart: always
    networks:
      - backend

  garpix_backend:
    container_name: garpix_backend
    build: ./backend
    command: ["uvicorn", "app.app:app", "--host", "0.0.0.0", "--port", "8000"]
    volumes:
      - ./backend:/app
    restart: always
    ports:
      - "8000:8000"
    env_file: 
      - backend/.env
    depends_on:
      - garpix_postgres
    networks:
      - backend

  garpix_frontend:
    container_name: garpix_frontend
    build: ./frontend
    ports:
      - "8501:8501"
    volumes:
      - ./frontend:/app
    depends_on:
      - garpix_backend
    networks:
      - backend


networks:
  backend:
